#!/usr/bin/env node

require('dotenv').config();

const path = require('path');

const argList = require(path.join(__dirname, 'lib', 'helpers', 'parseargs.js'))(process.argv.slice(2));
const commandList = require(path.join(__dirname, 'lib', 'helpers', 'commands.js'))();

const parseCommand = function (inputargs, commands) {
  const args = inputargs.keys();
  const cmd = args.next().value;

  const cmds = [...commands.keys()];

  let valid;

  cmds.forEach((cmdList) => {
    if (cmdList.includes(cmd)) {
      valid = true;
      commands.get(cmdList).apply(null, [...args]);
    }
  });

  if (!valid) {
    commands.help();
    process.exitCode = 1;
  } else {
    process.exitCode = 0;
  }

  return;
};

parseCommand(argList, commandList);

