#!/usr/bin/env node

const { keys } = Object;
const path = require('path');

const args = require(path.join(__dirname, 'lib', 'helpers', 'parseargs.js'))(process.argv.slice(2));
const commands = require(path.join(__dirname, 'lib', 'helpers', 'commands.js'));

const parseCommand = function (inputargs, inputcommands) {
  const args = inputargs.keys();
  const commands = [...inputcommands.keys()]; //use args instead?

  const cmd = args.next().value;
  let valid;

  commands.forEach((cmdList) => {
    if (cmdList.includes(cmd)) {
      valid = true;
      inputcommands.get(cmdList).apply(null, [...args]);
    }
  });

  if (!valid) {
    // printer: command invalid
    // fire help command
    process.exitCode = 1;
  } else {
    process.exitCode = 0;
  }

  return;
};

parseCommand(args, commands);

