#!/usr/bin/env node

const os = require('os');
const path = require('path');
const spawn = require(path.join(__dirname, '..', 'helpers', 'spawn'));
const { say, shout } = require(path.join(__dirname, '..', 'helpers', 'printer'));

const isInstalled = (cmd) => {
  return spawn({}, 'command', '-v', cmd).stdout.toString().length;
}

const subroutines = {
  darwin() {
    // this prevents pollution of the module space in the project
    if (!isInstalled('live-server')) spawn('npm', '--prefix', projectdirectory, 'install', 'live-server', '-g');
  },
  linux() {
  },
  win32() {
  }
}[os.platform()]();

shout('sandl has finished installing');
say('please configure with\n\nsandl config username=<GITHUB_USERNAME> token=<GITHUB_PERSONAL_ACCESS_TOKEN>');
say('\nfor information on generating github access token, see https://developer.github.com/v3/guides/getting-started/#oauth');
say('for webassembly modules, it is recommended to install and use the Rust ecosystem');

