#!/usr/bin/env node

const fs = require('fs');
const { spawnSync } = require('child_process');

// check for operating system

// check for and install git
// check for and install static-server
// globally install wargo and init a rust folder
// query for git username

